# Generated by Django 5.1 on 2024-09-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Обращения', '0002_alter_application_message_alter_application_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='type_app',
            field=models.CharField(choices=[('RING', 'Обратный звонок'), ('COST', 'Стоимость проекта'), ('APPL', 'Заявка')], default='RING', max_length=4, verbose_name='Тип обращения'),
        ),
    ]
