# Generated by Django 5.1 on 2024-09-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Обращения', '0004_alter_application_type_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='type_app',
            field=models.CharField(choices=[('ring', 'Обратный звонок'), ('cost', 'Стоимость проекта'), ('app_site', 'Заявка на сайт'), ('app_bot', 'Заявка на чат-бота'), ('app_design', 'Заявка на дизайн'), ('app', 'Заявка из раздела проекты')], default='RING', max_length=10, verbose_name='Тип обращения'),
        ),
    ]
