# Generated by Django 5.0.7 on 2024-07-18 14:56

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='reviews', verbose_name='Фотография для галереи')),
                ('alt', models.CharField(max_length=255, verbose_name='Альтернативный текст')),
                ('text', models.TextField(max_length=400, verbose_name='Текст отзыва')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
