# Generated by Django 5.1 on 2024-09-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Отзывы', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Альтернативный текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст отзыва'),
        ),
    ]
