# Generated by Django 5.1 on 2024-09-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Отзывы', '0002_alter_review_alt_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videoreviews', verbose_name='Видео-отзыв'),
        ),
    ]
