# Generated by Django 5.1 on 2024-09-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Отзывы', '0003_review_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='review',
            name='src',
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videoreviews', verbose_name='Видео-отзыв, в формате mp4'),
        ),
    ]
