# Generated by Django 5.1 on 2024-09-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Отзывы', '0004_remove_review_alt_remove_review_src_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='videoreviews', verbose_name='Постер для видео-отзыва'),
        ),
    ]
