services:
    web-studio-api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: web-studio-api
        restart: always
        volumes:
            - ./api:/api
            - ./api/db.sqlite3:/api/db.sqlite3
            - ./static:/static
            - ./media:/media:rw
        #ports:
        #    - "5008:443"
        #env_file:
        #    - .env
        networks:
            - proxy
            - web-studio-app
    web-studio-ui:
        build:
            context: ./ui
            dockerfile: Dockerfile
        container_name: web-studio-ui
        restart: always
        volumes:
            - ./ui:/app
            - ./static:/static
            - ./media:/media
        ports:
            - "3000:3000"
        networks:
            - proxy
            - web-studio-app

networks:
    proxy:
        external: true
        name: proxy
    web-studio-app:

volumes:
    logs:
