services:
    web-studio-api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: web-studio-api
        restart: always
        volumes:
            - ./api:/api
            - ./api/db.sqlite3:/api/db.sqlite3
            - ./static:/static
            - ./media:/media:rw
        #ports:
        #    - "5008:443"
        #env_file:
        #    - .env
        networks:
            - proxy
            - web-studio-app
    web-studio-ui:
        build:
            context: ./ui
            dockerfile: Dockerfile
        container_name: web-studio-ui
        restart: always
        volumes:
            - ./ui:/app
            - ./static:/app/static
            - ./media:/app/media
        ports:
            - "3000:3000"
        networks:
            - proxy
            - web-studio-app
    nginx:
        image: nginx:latest
        container_name: web-studio-nginx
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./ui/dist/client:/usr/share/nginx/html
            - ./static:/app/static
            - ./media:/app/media
        #ports:
        #    - "80:80"
        depends_on:
            - web-studio-api
            - web-studio-ui
        networks:
            - proxy
            - web-studio-app

networks:
    proxy:
        external: true
        name: proxy
    web-studio-app:

volumes:
    logs:
