services:
    web-studio-api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: web-studio-api
        restart: always
        volumes:
            - ./api:/api
            - ./api/db.sqlite3:/api/db.sqlite3
            - webstudio_static_volume:/api/static
            - webstudio_media_volume:/api/media
        #ports:
        #    - "5008:443"
        #env_file:
        #    - .env
        networks:
            - proxy
            - web-studio-app
    web-studio-ui:
        build:
            context: ./ui
            dockerfile: Dockerfile
        container_name: web-studio-ui
        restart: always
        volumes:
            - webstudio_static_volume:/app/static
            - webstudio_media_volume:/app/media
        ports:
            - "3000:3000"
        networks:
            - proxy
            - web-studio-app

networks:
    proxy:
        external: true
        name: proxy
    web-studio-app:

volumes:
    logs:
    webstudio_static_volume:
        external: true
    webstudio_media_volume:
        external: true
