services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: web-studio-api
        restart: always
        volumes:
            - ./api:/api
            - ./api/db.sqlite3:/api/db.sqlite3
            - /static:/api/static
            - /media:/api/media
        #ports:
        #    - "5008:443"
        #env_file:
        #    - .env
        networks:
            - proxy
            - web-studio-app
    ui:
        build:
            context: ./ui
            dockerfile: Dockerfile
        container_name: web-studio-ui
        restart: always
        volumes:
            - /static:/app/static
            - /media:/app/media
        ports:
            - "3000:3000"
        networks:
            - proxy
            - web-studio-app
    nginx:
        image: nginx:latest
        container_name: web-studio-nginx
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - /static:/app/static
            - /media:/app/media
        ports:
            - "49152:49152"
        depends_on:
            - api
            - ui
        networks:
            - proxy
            - web-studio-app

networks:
    proxy:
        external: true
        name: proxy
    web-studio-app:

volumes:
    logs: