# Generated by Django 5.1 on 2024-09-10 13:27

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='projects', verbose_name='Обложка проекта')),
                ('cover_alt', models.CharField(max_length=500, verbose_name='Альтернативный текст')),
                ('title', models.TextField(max_length=500, verbose_name='Текст отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
