# Generated by Django 5.1 on 2024-09-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Проекты', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
