# Generated by Django 5.1 on 2024-09-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Проекты', '0004_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_alt_color',
            field=models.BooleanField(default=False, verbose_name='Заголовок белого цвета'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_alt',
            field=models.CharField(max_length=500, verbose_name='Альтернативный текст обложки'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок проекта'),
        ),
    ]
