# Generated by Django 5.1 on 2024-09-13 07:23

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Проекты', '0005_project_title_alt_color_alter_project_cover_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_314',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='projects', verbose_name='Обложка проекта для экранов c шириной контента 314px'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_380',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='projects', verbose_name='Обложка проекта для экранов c шириной контента 380px'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_470',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='projects', verbose_name='Обложка проекта для экранов c шириной контента 470px'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_560',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='projects', verbose_name='Обложка проекта для экранов c шириной контента 560px'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_960',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='projects', verbose_name='Обложка проекта для экранов c шириной контента 960px'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='projects', verbose_name='Обложка проекта для экранов c шириной контента 1152px'),
        ),
    ]
