# Generated by Django 5.1 on 2024-09-13 15:03

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Проекты', '0006_project_cover_314_project_cover_380_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cover_470',
        ),
        migrations.AddField(
            model_name='project',
            name='cover_740',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='projects', verbose_name='Обложка проекта для экранов c шириной контента 740px'),
        ),
    ]
