# Generated by Django 5.1 on 2024-09-18 11:51

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Проекты', '0007_remove_project_cover_470_project_cover_740'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на проект'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Особенность проекта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Проекты.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Особенность проекта',
                'verbose_name_plural': 'Особенности проекта',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='presentations', verbose_name='Презентация проекта')),
                ('alt', models.CharField(max_length=500, verbose_name='Альтернативный текст изображения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Проекты.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображения проекта',
            },
        ),
    ]
