# Generated by Django 5.1 on 2024-09-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Проекты', '0008_project_project_link_feature_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_detail',
            field=models.BooleanField(default=False, verbose_name='Включить детальное описание проекта'),
        ),
    ]
