# Generated by Django 5.1 on 2024-09-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Проекты', '0009_project_enable_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Презентация проекта', 'verbose_name_plural': 'Презентации проекта'},
        ),
    ]
