name: CI/CD Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  #        port: ${{ secrets.PORT }}
                  script: |
                      cd /home/web_studio_site
                      git pull origin main
                      docker-compose down
                      docker-compose up -d --build

#    - name: Set up SSH
#      uses: webfactory/ssh-agent@v0.5.3
#      with:
#        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#    - name: Copy files via SCP
#      run: scp -r ./* root@217.25.88.125:/home/web_studio_site

#    - name: Rebuild and restart Docker containers
#      run: |
#        ssh root@217.25.88.125 << 'EOF'
#          cd /home/web_studio_site
#          docker-compose down
#          docker-compose up -d --build
#        EOF
#    - name: Checkout code
#      uses: actions/checkout@v4
