name: CI/CD Deploy

on:
    push:
        branches:
            - master

jobs:
    run_pull:
        name: run pull
        runs-on: ubuntu-latest

        steps:
            #- name: install ssh keys
            # check this thread to understand why its needed:
            # https://stackoverflow.com/a/70447517
            #  run: |
            #      install -m 600 -D /dev/null ~/.ssh/id_rsa
            #      echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            #      ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts
            #      ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            #- name: connect and pull
            #  run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /home/web_studio_site && git checkout master && git pull && exit"
            #- name: cleanup
            #  run: rm -rf ~/.ssh
            #    deploy:
            #        runs-on: ubuntu-latest
			  - name: Checkout code
				uses: actions/checkout@v2
			  - name: Set up SSH
				run: |
				  mkdir -p ~/.ssh
				  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
				  chmod 600 ~/.ssh/id_rsa
				  ssh-keyscan github.com >> ~/.ssh/known_hosts
		  
			  - name: Execute remote SSH commands
				uses: appleboy/ssh-action@v0.1.3
				with:
				  host: ${{ secrets.HOST }}
				  username: ${{ secrets.USERNAME }}
				  key: ${{ secrets.SSH_PRIVATE_KEY }}
				  script: |
					cd /home/web_studio_site
					git remote set-url origin git@github.com:EliasHR/web_studio_site.git
					git checkout master
					git pull origin master
					docker-compose down
					docker-compose build
					docker-compose up -d

#    - name: Set up SSH
#      uses: webfactory/ssh-agent@v0.5.3
#      with:
#        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#    - name: Copy files via SCP
#      run: scp -r ./* root@217.25.88.125:/home/web_studio_site

#    - name: Rebuild and restart Docker containers
#      run: |
#        ssh root@217.25.88.125 << 'EOF'
#          cd /home/web_studio_site
#          docker-compose down
#          docker-compose up -d --build
#        EOF
#    - name: Checkout code
#      uses: actions/checkout@v4
