name: CI/CD Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Execute remote SSH commands
              uses: appleboy/ssh-action@v0.1.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  #key: ${{ secrets.SSH_PRIVATE_KEY }}
                  password: ${{ secrets.PASSWORD }}
                  script: |
                      ssh-keyscan github.com >> ~/.ssh/known_hosts
                      cd /home/web_studio_site
                      git remote set-url origin git@github.com:EliasHR/web_studio_site.git
                      git pull
                      docker-compose down
                      docker-compose build
                      docker-compose up -d

#                      g
#                     git checkout master
#                     git pull origin master
